#!/bin/bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/config/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/nginx-vhosts/functions"

app="$1"; verify_app_name "$app"

eval "$(config_export global)"
eval "$(config_export app "$app")"

CONFIG_FOLDER="$DOKKU_ROOT/$APP/nginx.conf.d"
CONFIG_FILE="$CONFIG_FOLDER/ua_block.conf"
[[ -d "$CONFIG_FOLDER" ]] || mkdir "$CONFIG_FOLDER"

if  [ -z "$BLOCKED_USER_AGENTS" ]; then
  dokku_log_info1 "Blocking user agents..."
  echo "if (\$http_user_agent ~ ($BLOCKED_USER_AGENTS) ) {" >> $CONFIG_FILE
  echo "  return 403;"                                      >> $CONFIG_FILE
  echo "}"                                                  >> $CONFIG_FILE
  chown dokku:dokku $CONFIG_FILE
else
  dokku_log_info1 "Unblocking user agents..."
  rm -f $CONFIG_FILE
fi

restart_nginx
